# Generated by Django 5.0 on 2024-01-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(to='moneyapp.sub_category'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumption',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Plastic_card',
        ),
    ]
