# Generated by Django 4.1.7 on 2024-01-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0002_category_sub_category_consumption_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='status',
            field=models.IntegerField(choices=[(1, 'Basic'), (2, 'Standard'), (3, 'Premium')], default=1),
        ),
    ]
