# Generated by Django 5.0.1 on 2024-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0004_alter_consumption_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
